### ISSUE TITLE
Update Google Analytics to G4

### ISSUE THREAD

**Issue by shrayshray** [Metro-Records/la-metro-councilmatic#1003]
Here is the new G4 Property for Google Analytics.  Please update the current property on the website.

 <script async src=https://www.googletagmanager.com/gtag/js?id=G-9E47Y9QH06></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-9E47Y9QH06'); </script>

**Comment by hancush** [comment]
Hey, @shrayshray – the new Google code has been deployed to the staging site. Can you confirm you're seeing traffic come through?

**Comment by xmedr** [comment]
@shrayshray Just a confirmation that the new analytics code is pushed up onto the staging site along with the mobile/accessibility updates!

**Comment by hancush** [comment]
@xmedr to get the new code deployed to the live site ASAP.
