### ISSUE TITLE
Searches for multiple tags yeild zero results

### ISSUE THREAD

**Issue by shrayshray** [Metro-Records/la-metro-councilmatic#1011]
I'm currently trying to locate reports tagged with both "Testimony" and "Public Hearing". I was expecting to be able to build a search for multiple tags in the search bar. When I tried to, I got zero results. Here are the steps I took:
1.  Type "Testimony" in the search bar and select the term from the suggestion drop down, then click search
2. Select "Result type" = "Tag Search", which yields 21 results. 
3. Go back to the search bar, type "Public Hearing" and select it from the suggestion drop down, then run the search, which yields 21 results. 
4. After verifying some of these results are tagged with both "Testimony" and "Public Hearing", select "Result type" = "Tag Search"
5. Get zero results. 
Am I incorrect in my assumption I should be able to build a search for multiple tags in the search bar?

I'm able to get the results I expect using this process:
1. Click on the tag "Testimony" either on a search result in the list, or in the side bar of a report
2. On the new results page, clear "Testimony" from the search bar but not from the filters
3. Type "Public Hearing" and select it from the suggestion drop down, then run the search, which yields 21 results. 
4. Select "Result type" = "Tag Search"
5. Get 4 results with both tags

**Comment by hancush** [comment]
There are a couple of relevant sections in the code:

- On the front end, we parse the query from the search bar to send to the server [here](https://github.com/Metro-Records/la-metro-councilmatic/blob/70b6e171b9b0033511b55c43ddd8f87a417a8179/lametro/static/js/autocomplete.js#L139).
- On the back end, we convert the parsed query to a SearchQuerySet [here](https://github.com/Metro-Records/la-metro-councilmatic/blob/70b6e171b9b0033511b55c43ddd8f87a417a8179/lametro/forms.py#L63).

I suspect but am not 100% sure that one of these might not be behaving correctly.

**Comment by hancush** [comment]
Fixed in #1019.
