### ISSUE TITLE
Add phrase in quotes help text to search bar

### ISSUE THREAD

**Issue by hancush** [Metro-Records/la-metro-councilmatic#1013]
Add some placeholder text to the search bar indicating that you can "search for a phrase" using double quotes

**Comment by xmedr** [comment]
@monkruman maybe you could help me out with this one. I worked on this for a while but the search bar isn't a regular input so adding placeholder text has been tough 😖 

It's manipulated by a package called select2 which does have a way to [change the placeholder text](https://select2.org/placeholders). However it breaks the search function and I haven't found a way to circumvent that within the package for multiple select ajax inputs.

After a while, I tried hacking around with my own js to get it to display the placeholder. I got *so* close, but couldn't get it quite right. It involved adding a placeholder attribute to the empty input even though select2 dynamically and frequently clears the placeholder attribute, and minimizes the width of the input, cutting it off even when it does show.

I'm down to pair if you'd like to and are available this week, but if we can't find a solution maybe we resort to putting this help text in the paragraph above the search bar?

**Comment by antidipyramid** [comment]
@xmedr Sure! How have you tried to add the placeholder text to the select2 search bar?

I made this change [here](https://github.com/Metro-Records/la-metro-councilmatic/blob/6e34d5a2832a1a66836dcd8326d2c2a128a657e7/lametro/static/js/autocomplete.js#L82) and it seems to do what I expect without breaking the search:

```js
...
    $input.select2({
        tags: true,
	placeholder: "Enter your search here",
        ajax: {
...

```

**Comment by xmedr** [comment]
You're right, I had no idea this was there! I was putting just the placeholder bit in the script tags of each search page so I was probably reinitializing select2 and overwriting all this. Thank you so much!

**Comment by hancush** [comment]
Done in #1031
