### ISSUE TITLE
Duplicate Entries After Membership Change

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1016]
Hi Team,

We are seeing duplicate entries for the Measure M Independent Taxpayer Oversight Committee members page after making changes to the members. It seems like the old member entries are not getting removed. Please see below:

![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/074288fb-7831-40ee-a0de-20c5de5f5f31)

![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/8fb2c155-c063-4c53-9342-bd72f6314ff1)

**Comment by hancush** [comment]
Fixed!

<img width="965" alt="Screen Shot 2023-09-12 at 3 59 12 PM" src="https://github.com/Metro-Records/la-metro-councilmatic/assets/12176173/fdcaed24-6dfe-405d-87e6-7af7c0882f5b">
