### ISSUE TITLE
9/13/23 Measure M Meeting not showing in "Recent Meetings" section

### ISSUE THREAD

**Issue by shrayshray** [Metro-Records/la-metro-councilmatic#1017]
On Wednesday, 9/13/23, Granicus experienced an outage before and through the duration of the Measure M Independent Taxpayer Oversight Committee. The broadcast was started, but the meeting status never changed to “In Progress”. As a result, the links to watch never showed on the site (will address this in a separate issue), and the meeting is not showing in the "Recent Meetings" section of the website, I'm assuming because the scraper never saw it as "In Progress" and "Concluded". Is there a way on the Datamade side to manually log it as concluded so it will show in this section? Would our best bet maybe be to restart and stop it once all Granicus issues are confirmed as resolved?

**Comment by hancush** [comment]
Done!
