### ISSUE TITLE
Gloria Roberts Information Changes

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1020]
We need to change a few details for Gloria Roberts on the site.

We need to change the following:
•	Remove the “(Interim)” part on their title
•	Remove the “District appointee” identifier. If it has to be replaced we can replace it with “Governor Appointee”.
•	Make sure these changes are reflected in all Committees where Gloria is a part of.

 
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/5eafc891-b2a3-4e2b-8af6-4328d836b730)
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/a9c668fb-029b-4762-b1e9-6b0c9548fefa)

Thank you!

**Comment by neilarellano** [comment]
@hancush can we look into this please? Thank you.

**Comment by neilarellano** [comment]
Hi @hancush . Thanks for removing the interim reference on Gloria Roberts' title. The site still shows that she is a  "District Appointee". Are we able to change this reference or remove it?

**Comment by hancush** [comment]
@neilarellano Yes, working on it.

**Comment by hancush** [comment]
Fixed via #1028.
