### ISSUE TITLE
Tag search doesn't include bill type matches

### ISSUE THREAD

**Issue by antidipyramid** [Metro-Records/la-metro-councilmatic#1026]
After merging in #1019, tag searches no longer include matches for bill type.

<img width="1400" alt="Screen Shot 2023-10-04 at 12 28 16 PM" src="https://github.com/Metro-Records/la-metro-councilmatic/assets/36973363/e34a254f-8c91-46d6-b047-fe9046ceb6ec">

**Comment by hancush** [comment]
Fixed in #1027.
