### ISSUE TITLE
Home: Search suggestions not loading

### ISSUE THREAD

**Issue by shrayshray** [Metro-Records/la-metro-councilmatic#1030]
In the search bar on the Home page, search suggestions are not showing. I've tried several queries, and the drop down shows "Results could not be loaded." This is happening in both Firefox and Chrome. It is not happening on the Search page, just in the search bar on the Home page.
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/28063988/e4f6950d-2346-4376-9786-9bcedeb5da3e)

**Comment by hancush** [comment]
Done in #1032
