### ISSUE TITLE
Home: Update background image on search bar

### ISSUE THREAD

**Issue by shrayshray** [Metro-Records/la-metro-councilmatic#1033]
The system map image in the background of the search bar needs to be updated. The line names are pre-2020 and routes/stations are are missing the K Line and Regional Connector updates. Please replace the current image with this one:
https://uc26beceb2e1aa705ca9c099d827.dl.dropboxusercontent.com/cd/0/inline2/CF9heMXmw4w4lhRgqaiykRIdajHIUwphyHkIpeoz3mS3mxzNGukJrW835wMLaFOn2cG-HG1ZCEqL0PhLqa0hK6-wbWifRdS4zhN_ZlgIMy8pbl71Twebw_2k85qDS-zpLmST7P2whZV6AJFxnpnNk812w1Qen5hoLhpmfcZa22fCz5k98UL3tNuNKvWNhU7jo4cP-9xwfJUIxa_t5IlteHhNQD7H6_V7grrIObnBZg64zGk0ZfwNzQNkBUyjg8VTsi2Lqcd5ZUbQnoqQcF1_t0Td5vJhXKn5kd3DmJI5q0Ri0aQIiETrsk0oeRxqmbb3gkhJprasRM1eE4PulO8vwWUO5Y9-LCAqmm3iCzdYZgoZ7wG4Wots5LLBUwdJFue6VXU/file

**Comment by xmedr** [comment]
@shrayshray Can do! It looks like this link is broken for me, would you happen to have another? Or maybe sharing isn't enabled?

**Comment by shrayshray** [comment]
@xmedr Sorry the direct link didn't work - it's the 3rd item under "Over Maps" on this page: https://www.metro.net/riding/guide/system-maps/ "Rail and Busway (Go Metro) Map"
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/28063988/98025f5f-fea0-4af2-a2e5-9d04f717b2b2)
