### ISSUE TITLE
Discontinue showing "Recap" link

### ISSUE THREAD

**Issue by shrayshray** [Metro-Records/la-metro-councilmatic#1041]
In #753 logic was deployed on the events page to display a link to the meeting Recap webpage next to a meeting until the meeting's Minutes were available, then replace the Recap link with the Minutes link.
The Recap webpage is no longer being updated. Please revise the logic to no longer show the Recap link at all, and simply show the link to the Minutes once they are available.

![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/28063988/c2983a73-8758-4943-bfe3-af49bb0108c7)

**Comment by xmedr** [comment]
Dec 8 update: this should be working as expected on the new heroku staging site
