### ISSUE TITLE
Updates to analytics reporting

### ISSUE THREAD

**Issue by shrayshray** [Metro-Records/la-metro-councilmatic#1043]
We'd like the following changes to tag analytics reports:
1. File naming convention to start with the date in this format - YYYY-MM-DD
2. Reports run on the first of every month. This seems to be what was established in #812, but it now looks like reports are running quarterly.

**Comment by shrayshray** [comment]
@antidipyramid is this issue still in progress? The latest report I'm seeing are from 10-31-2023. We'd like to prioritize this fix.

**Comment by antidipyramid** [comment]
We should make sure that the year comes first in the file name.

**Comment by antidipyramid** [comment]
Hi @shrayshray, here are the three most recent analytics files on Google Drive. Is this how we expect the files to be named?

<img width="320" alt="Screenshot 2024-03-05 at 3 58 15 PM" src="https://github.com/Metro-Records/la-metro-councilmatic/assets/36973363/ab7914c7-bf03-4e24-b17a-a7caac880056">
