### ISSUE TITLE
Spanish audio links not showing

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1044]
Greetings Datamade Team,

We ran into an issue where the Spanish stream for Planning and Programming was not showing up.
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/737373dc-591f-4823-8c0d-e8f8bbcb5542)

We checked and found that metro.legistar.com and metro.granicus.com show the links with no problem:
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/5f4862ed-4c15-49fb-a43a-a35fdd948974)
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/dc6f17e5-0951-4f46-a75b-abc9a1b742f8)

We added a temporary alert showing the stream link for now. Are we able to investigate what caused this issue?

Thanks!

**Comment by hancush** [comment]
Diagnosis from email:

---

Hi, all – We use the API to find Spanish counterparts for English-language events. That query looks like: 

https://webapi.legistar.com/v1/metro/events/?$filter=EventBodyName eq '${BODY_NAME_SAP}' and EventDate eq datetime'{EVENT_DATE}'

For example, to find the Spanish partner for today's Ops, Safety, Customer Service meeting:

https://webapi.legistar.com/v1/metro/events/?$filter=EventBodyName%20eq%20%27Operations,%20Safety,%20and%20Customer%20Experience%20Committee%20(SAP)%27%20and%20EventDate%20eq%20datetime%272023-11-16T00:00:00%27

You can see that this returns no results, despite the SAP event appearing on InSite. If you remove the date parameter, we see only one meeting returned for the SAP version of this body, again despite there being many more on InSite: https://webapi.legistar.com/v1/metro/events/?$filter=EventBodyName%20eq%20%27Operations,%20Safety,%20and%20Customer%20Experience%20Committee%20(SAP)%27

Compare this to the results for meetings of the English-language body, which include all events from InSite: https://webapi.legistar.com/v1/metro/events/?$filter=EventBodyName%20eq%20%27Operations,%20Safety,%20and%20Customer%20Experience%20Committee%27

Is it possible to control whether events should appear in the API? If so, was this toggled off for SAP events? Any other reason why SAP events might not appear in the API?

Thanks for your help,
Hannah

---

@camachoo is looking into this with Granicus.
