### ISSUE TITLE
FY24 Meeting Calendar Update

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1052]
Hi Team!

There are a few changes to the Ad Hoc Olympics meeting dates. I am attaching the updated file here.
[FY24 Committee & Board Calendar - Updated.pdf](https://github.com/Metro-Records/la-metro-councilmatic/files/13824719/FY24.Committee.Board.Calendar.-.Updated.pdf)

Thank you!

**Comment by antidipyramid** [comment]
@neilarellano The calendar on the live site has been updated!

**Comment by neilarellano** [comment]
Thank you all!
