### ISSUE TITLE
Fix CalTrans board member on map and member listing page

### ISSUE THREAD

**Issue by antidipyramid** [Metro-Records/la-metro-councilmatic#1056]
Since we're now pulling board member titles from Legistar (#1045), we need to look for `CalTrans` instead of `Caltrans` when parsing board member titles.

(e.g. Badge below should be `CalTrans` and show CalTrans geography on map)

<img width="690" alt="Screen Shot 2024-01-09 at 9 23 34 AM" src="https://github.com/Metro-Records/la-metro-councilmatic/assets/36973363/d3939c5e-c26f-41e2-a479-4d007932c70b">

**Comment by antidipyramid** [comment]
We'll also update the spelling on CalTrans references throughout the site.

**Comment by shrayshray** [comment]
@antidipyramid CORRECTION!! "Caltrans" is the correct format, not "CalTrans". I misspoke in our meeting yesterday. I have updated the Notes field on Gloria Roberts' record to the correct format. 
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/28063988/5c0b455d-cb86-4f12-bc8c-841a5732afee)

**Comment by antidipyramid** [comment]
@shrayshray No worries! Thanks for checking on this. We'll be on the lookout for this update to Gloria Robert's title.

**Comment by antidipyramid** [comment]
@antidipyramid will delete the duplicate entry on the board members page now that the spelling has been updated.
