### ISSUE TITLE
Boardagendas Site Application Error

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1062]
We are getting an Application Error when loading the site. Please see below:

![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/1cce8e9f-b95b-4a88-8962-4d4bf5e5c1f1)

**Comment by shrayshray** [comment]
This occurred during the 1/18/24 Operations, Safety and Customer Experience Committee meeting which began at aprox 1:05pm PST. The site was loading intermittently as of 1:22pm, and consistently as of 1:32pm. 
Per @antidipyramid via email, "It seems like a large number of people are trying to access the site right now. We’ve increased the server capacity and will continue to monitor the site as the meeting goes on.
We’ll also continue investigating what caused the bottleneck and how to avoid it in the future."

**Comment by antidipyramid** [comment]
[Link to load test results](https://docs.google.com/document/d/1r7Byb14QHqBsoa6Y4Sd0JBT4Dd1dEJv8kNk2l5Vz7kE/edit)

**Comment by antidipyramid** [comment]
2/2 update: we've doubled the server memory of our dynos on Heroku. So far, this seems to fix our memory woes.
