### ISSUE TITLE
Bypass instructions on error pages

### ISSUE THREAD

**Issue by shrayshray** [Metro-Records/la-metro-councilmatic#1063]
It looks like our custom error pages were not included in the Heroku migration. This was noticed in #1062  and in an issue reported via email 1/16/24 when report links from the Planning and Programming meeting page were going to 404 error pages. All error pages should have the https://metro.legistar.com/Calendar.aspx link and the https://metro.legistar.com/Legislation.aspx links on them with the standard text we had i.e. "If you are having issues..." to direct people back to metro.legistar.com if there are errors on boardagendas.metro.net

**Comment by antidipyramid** [comment]
Hi @shrayshray, we deployed an update that should re-instate the error (500) pages. However, It looks like we don't have a custom 404 page. This is what it looks like right now:

<img width="1437" alt="Screenshot 2024-01-23 at 9 37 53 AM" src="https://github.com/Metro-Records/la-metro-councilmatic/assets/36973363/a3318d7c-49a6-401c-9743-f73228a95f1a">

Would you like us to add any links to this page as well?

**Comment by antidipyramid** [comment]
We'll add Calendar and Legistar links to the 500 pages as well.
