### ISSUE TITLE
Committee Members Issue

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1081]
Hi Team,

We noticed that there are members that are not on Leigstar for a committee but are still showing up on the site. Please see below:

Through the Committees link, there are some corrections needed:
Planning & Programming is showing Holly Mitchell as a member. She should be removed.
Also showing Gloria Roberts twice. Please remove the interim.
 
Operations Committee is showing Katy Yaroslavsky as a member. She should be removed.
Also showing Gloria Roberts twice. Please remove the interim.
 
Measure M has two Chairs showing. It should only be Richard Stanger.
We need to have Measure M not shown on the Committees page at all.

Finance & Budget committee is also showing Gloria Roberts twice. Please remove the interim.

Ad Hoc 2028 is showing Gloria Roberts twice. Please remove the interim.

**Comment by antidipyramid** [comment]
@neilarellano I've updated the live site with the committee membership changes you outlined above.

There are currently two Measure M committees shown on the listing page. Should we remove both of them?

**Comment by neilarellano** [comment]
Yes. Please remove both of them. They should not show up on the Committees page at all.

Thanks!
