### ISSUE TITLE
Board Report Keyword Facets - Katy Yaroslavsky tags under "Subject", not "Motion By"

### ISSUE THREAD

**Issue by shrayshray** [Metro-Records/la-metro-councilmatic#1090]
When relevant Board Members are tagged on reports, their names should appear under the "Motion By" facet. Katy Yaroslavsky is appearing under the "Subject" facet. Here are some examples:
https://boardagendas.metro.net/board-report/2023-0773/
https://boardagendas.metro.net/board-report/2023-0657/
https://boardagendas.metro.net/board-report/2024-0208/

Facets are determined by the Class assigned in the Semaphore model. The "Motion By" facet is filtered based on Class = Board Member. Katy does have  Class = Board Member:
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/28063988/51989ea2-9329-49ac-aa54-8b1b9e80c3e5)

Please investigate why her name is not appearing under the Board Member facet on the website.

**Comment by antidipyramid** [comment]
@shrayshray is it possible that the Semaphore model listed a different concept class for Katy Yaroslavsky for a short period of time in the past? It looks like we only have six board reports with a "Katy Yaroslavsky" subject tag on the site.

One thing we could try is simply deleting the incorrect tag from the database and seeing if the problem reoccurs. Now that we know the Semaphore model is correct, that would pinpoint our site/scrapers as the source of the issue.

**Comment by shrayshray** [comment]
@antidipyramid yes, it's possible the class for Katy Yaroslavsky was incorrect in the past. Deleting the incorrect tag and seeing if the problem reoccurs sounds like a good plan.

**Comment by shrayshray** [comment]
@xmedr thank you! We'll keep an eye on whether she repopulates into the "Motion By" facet.

**Comment by antidipyramid** [comment]
Katy Yaroslavsky is now not showing up in the "Motion By" section of board reports (e.g. [2024-0365](https://boardagendas.metro.net/board-report/2024-0365/)).

**Comment by hancush** [comment]
@antidipyramid Want to try running the `refresh_guid` management command manually, to see if that brings her in? It should be triggered by Semaphore after it syncs with Legistar nightly, but it's possible that the trigger is failing.

**Comment by antidipyramid** [comment]
Yep, that did it. Katy Yaroslavsky is now listed under "Motion By" in 2024-0365. Thanks, @hancush.

**Comment by hancush** [comment]
Cool, @antidipyramid. We'll want to figure out why that trigger isn't working. Do you see any requests recent requests to `/refresh-guid/` in our traffic history?

**Comment by antidipyramid** [comment]
@hancush I'm seeing daily requests to this path specifically: `/refresh-guid/9AD8E396-E6EF-483B-9DBD-C55F447C3992`.

**Comment by antidipyramid** [comment]
Refresh key was updated. Calls to `/refresh-guid/` should now work as expected.
