### ISSUE TITLE
Home: Update the link to Archive Search

### ISSUE THREAD

**Issue by shrayshray** [Metro-Records/la-metro-councilmatic#1092]
The link under the search bar to "Search the Metro Board Archive from 1952-2015 (Board Boxes 1994-Present)" needs to be updated.

please update to this URL: https://mtasearch01.metro.net:23352/apps/boardarchives/
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/28063988/9bc64e33-37a9-4b53-a0e4-3745023af545)

**Comment by xmedr** [comment]
@shrayshray this updated link is now on the live site!
