### ISSUE TITLE
Rules & Procedures Update

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1097]
Greetings Team!

We need to update our Rules & Procedures document with the attached PDF file. We need to host it within the site instead of linking to a media.metro.net location.
https://boardagendas.metro.net/about/#procedures

![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/5de510d7-8eeb-458f-813c-154caf132130)
[Board Rules Procedures Document Amended 20230808.pdf](https://github.com/Metro-Records/la-metro-councilmatic/files/15066504/Board.Rules.Procedures.Document.Amended.20230808.pdf)

Please let us know if you have any questions regarding this. Thanks!

**Comment by xmedr** [comment]
@neilarellano we've pushed this pdf change as well as the changes in #1098 to the live site. let us know if there's anything else we can do here!

**Comment by neilarellano** [comment]
hi @xmedr looks good!
I did notice that the previous table of contents shortcut for procedures is now gone.
Are we able to add that back but have it scroll to the "Board Room Rules and Procedures" section? I think that was the link I sent:
https://boardagendas.metro.net/about/#procedures

**Comment by xmedr** [comment]
Ah got it! I'll get that back in there then

**Comment by xmedr** [comment]
@neilarellano We've got that link back in there, leading to the same `#procedures` url!
