### ISSUE TITLE
Document Upload/Update Feature

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1100]
Are we able to set up a feature that will provide our team with the ability to upload the documents on boardagendas site on our own?

We may also need to have an inventory of documents on the site along with the updates that we sent in.

**Comment by antidipyramid** [comment]
@neilarellano What types of documents would the Metro team want to upload?

**Comment by antidipyramid** [comment]
From @camachoo: There are a small number of documents (e.g. Metro rules and procedures on the About page) that the Metro team would like to be able to upload themselves. 

@neilarellano, can you let us know exactly which documents you'd like to upload?

**Comment by neilarellano** [comment]
Hi @antidipyramid

We are looking mostly into the About Us page documents such as Metro Rules & Procedures and Code of Conduct for now.

@camachoo - are there any other documents that we may periodically update within the site?

**Comment by antidipyramid** [comment]
We'll focus on implementing the document upload functionality through Wagtail first before moving on to other site content.

**Comment by antidipyramid** [comment]
Addressed in #1173
