### ISSUE TITLE
About Us Updates

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1102]
Greetings Team!

We need to update a few things on our About Us page.

**Under Board Committees section, please update to the following text:**
"Per the Administrative Ordinance, the Board of Directors has 5 standing committees. The Chair of the Board of Directors may designate other standing and ad hoc committees subject to concurrence of the Board of Directors."
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/47939d33-84a5-465a-9865-531508846c84)

**Under Board Room Rules and Procedures section, please update the following sections:**

- For the first bullet point, update the highlighted text to:
“please sign up for public comment on the tablets available in the lobby before 9:45 a.m.”
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/68da49f3-37df-47bb-b0d1-c513440d27b2)

- For the second bullet point, update the highlighted text to:
“General public comment is only to be used for topics within the Board’s jurisdiction and items not listed on the agenda.”
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/a3c092cb-4814-4b52-a6e8-2e78feb41df9)

Thanks!

**Comment by xmedr** [comment]
@neilarellano the language has been adjusted! let me know if things look alright
