### ISSUE TITLE
"Measure M Independent Taxpayer Oversight Committee -​ Public Hearing" Not Showing Concluded Status

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1115]
Greetings!

I noticed that our Measure M Independent Taxpayer Oversight Committee -​ Public Hearing meeting is not showing as "concluded" and still shows as "upcoming" under "Today's Meetings" section.

![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/9b506ab7-0240-4bf9-a8fe-6ee966baa951)

It seems like this meeting did end properly as shown within insite. Please advise.

**Comment by antidipyramid** [comment]
The event in question doesn't have an `EventBroadcast`. I'm thinking we can just manually create an `EventBroadcast` for the meeting to patch this. Does that sound right to you, @hancush?

(Could have something to do with #1116?)

**Comment by hancush** [comment]
@antidipyramid Sure thing. Go for it!
