### ISSUE TITLE
Public Hearing Meetings Have An Extra Unknown Character

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1116]
Hi Team,

We made changes to these meeting bodies below:
Measure M Independent Taxpayer Oversight Committee - Public Hearing
Measure R Independent Taxpayer Oversight Committee - Public Hearing
Independent Citizens’ Advisory and Oversight Committee - Public Hearing

The original meeting bodies looked the same but had an extra unknown character between the dash and the space after it causing it to show as a question mark insite.

Just a heads up if this caused any issues on the site

**Comment by antidipyramid** [comment]
@neilarellano Do you still see this extra character in Legistar?

**Comment by neilarellano** [comment]
Hi @antidipyramid ,

These meeting bodies have been corrected within Legistar and do not have the extra character anymore.
