### ISSUE TITLE
FY25 New Term Membership Updates

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1120]
Greetings Team!

We have updated the committee memberships for the upcoming FY25 (July 1, 2024 - June 30, 2025).

I just wanted to double check if these will be updated automatically on July 1st or if we need to update these manually. Please advise.

Thanks!

**Comment by antidipyramid** [comment]
We'll need to update the legislative session object before July 1 in [this init file](https://github.com/Metro-Records/scrapers-lametro/blob/main/lametro/__init__.py) @antidipyramid
