### ISSUE TITLE
Agenda Items List Issue

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1121]
Hi Team,

The item list on agenda pages seem to not be available. I checked previous meetings that we know had the agenda item list and the list is not there.

**Comment by xmedr** [comment]
@neilarellano We've pushed an update that brings back those agenda list items. Let us know if anything else comes up here!

<img width="1416" alt="image" src="https://github.com/Metro-Records/la-metro-councilmatic/assets/114717958/f30debb1-d3f2-4611-94f6-1f2c5a99bd7a">
