### ISSUE TITLE
Executive Management and Construction Committees Membership Issues

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1126]
We noticed that the Executive Management Committee and Construction Committee shows the “Gloria Roberts (Interim)” member again. I believe we resolved this previously but it is showing up again. I checked with Legistar and the record no longer shows the “(Interim)” in the membership. We also noticed that memberships are not correct for these two Committees. Please resolve this one ASAP.

![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/8882975c-30cb-42cc-8589-d8b26fce5917)
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/468937fc-d092-412d-99ed-20d808941a07)
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/858c7a5f-43dd-42d9-a764-33b3cd7be133)

**Comment by antidipyramid** [comment]
@neilarellano I've manually removed the incorrect committee memberships from the site.

**Comment by neilarellano** [comment]
@antidipyramid

Construction Committee still shows Solis.
Executive Management Committee still shows Krekorian.

**Comment by antidipyramid** [comment]
@neilarellano I've also manually removed Solis and Krekorian from the Construction and Executive Management Committees, respectively.

**Comment by antidipyramid** [comment]
We'll need to do some investigation into why Gloria Roberts reappeared as an interim member. We probably would avoid these issues altogether by getting the `pupa clean` dashboard working again. @antidipyramid

**Comment by antidipyramid** [comment]
We'll track `pupa` progress in #1007
