### ISSUE TITLE
New Call-in Number for Public Comment

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#1167]
Hi Team,

Below is our new call-in number for public comments for Committee and Board Meetings, effective November 1, 2024. The access codes will remain the same. 

New call-in number: 1-888-978-8818

Can we please have the number changed. But before we make the changes, can you please send us the text that displays for the public comment instructions for language verification?

Thanks!

**Comment by antidipyramid** [comment]
Hi @neilarellano. Here's what the text looks like with the new number:

![Image](https://github.com/user-attachments/assets/80d1929d-40fe-490c-b500-b0c466e47d1c)

**Comment by neilarellano** [comment]
@antidipyramid this looks good. I just confirmed it with our board admin team. Thanks!
