### ISSUE TITLE
Autocomplete: Wait to initialize autocomplete until a token is retrieved

### ISSUE THREAD

**Issue by hancush** [Metro-Records/la-metro-councilmatic#655]
When initializing autocomplete, we check whether we need a token, conditionally retrieve one, and initialize the search. However, retrieving the token does not block, so there is a race condition where we might not get the token before we initialize search. This leads the search to display "Results could not be loaded" for the user.

This is rectified on subsequent visits, or if the user refreshes the page, but it would be ideal (and fairly negligible) to fix!

**Comment by antidipyramid** [comment]
Looks like this was fixed in #1030
