### ISSUE TITLE
Configure service to back up GitHub artifacts

### ISSUE THREAD

**Issue by hancush** [Metro-Records/la-metro-councilmatic#795]
From the emergency response memo:

> Leverage [an existing service](https://github.com/marketplace?category=backup-utilities) to back up the code and project artifacts (issues, pull requests, etc.) on a regular basis. Retain backups on a remote host, such as Amazon S3 or Dropbox, for a specified period, e.g., one week.

**Comment by hancush** [comment]
From @shrayshray:

> We'd like to do this and have it backup to a Dropbox on the [boardreport@metro.net](mailto:boardreport@metro.net) account which we will share with Datamade.

**Comment by antidipyramid** [comment]
@hancush An option like Rewind Backups (recommended by Github) seems to be a cloud host themselves that stores snapshots of repos in the past 30 days. From there, they offer an option to also upload data to Amazon S3 buckets that you can then manage independently. We'd want to set up the S3 bucket to also automatically delete this data after a certain time frame.

Because Metro wants to have access to the data from a Dropbox account, we also need to set up an automatic backup from S3 to Dropbox whenever a backup is uploaded to S3. It looks like that might be possible to use AWS Lambda to [send the file over to Dropbox](https://www.dropbox.com/developers/documentation/http/documentation#files-save_url).

**Comment by hancush** [comment]
@antidipyramid What's the pricing like for Rewind Backups?

**Comment by antidipyramid** [comment]
@hancush It's $4 per user per month. Since we have 6 users in our org, it'd be $24/month.

**Comment by hancush** [comment]
Thanks, @antidipyramid! I'm comfortable with that. As a first step, how about setting up backups to Rewind Backups, and sharing some screenshots/info about what that entails and how we access the backups. We can then evaluate with Metro whether they want to take the extra step to push backups to Dropbox.

**Comment by antidipyramid** [comment]
@hancush Sure. I think we might have to sign up for Rewind on the Datamade Github account first, though.

**Comment by hancush** [comment]
It looks like maybe S3 sync is only available to enterprise accounts, which are several hundred dollars per month. It might make more sense to set up a Metro org on GitHub, of which Shelly, Omar, and our dev team can be owners, and use that to access the backups from Rewind directly. Something to run by them at our next monthly call.

**Comment by hancush** [comment]
I will look into the story for creating a GitHub org for Metro to host the backups. Would we have to transfer ownership of the repos there? Etc.

**Comment by hancush** [comment]
I've reached out to the Rewind team to see if we can grant backup access on a per-repo basis. If we can, then we don't need to create a new org. But if we can't, then that might be the easiest path forward.

**Comment by hancush** [comment]
Update: It's not currently possible to grant access on a per-repo basis, so we can either:

- Continue to act as intermediaries between Metro and backups
- Create a new Metro org, of which Metro admins and at least one DataMade administrator are own of, and transfer ownership of the repositories we want to back up to that org
  - Since our repos are public, this should not impact our ability to clone them onto the server during deployment
  - The only tricky thing here is the actual scrape code: The current DataMade repository hosts the Metro scraper, as well as several other municipal scrapers. We would probably want to break the Metro code into its own repo and potentially remove it from DataMade's repo (and the upstream Open Civic Data repo), adding it instead as a submodule.

**Comment by hancush** [comment]
@shrayshray will confab with Omar and let us know whether Metro Library will create its own GitHub org or whether we should look into other options.

**Comment by hancush** [comment]
Metro will get green light to create their own Metro Lib org, then grant at least one DataMader admin access so we can start repo ownership transfers and backups.

**Comment by hancush** [comment]
I'll include this in the email to Omar, as well.

**Comment by shrayshray** [comment]
@hancush - @camachoo  set up a new GitHub Org which Metro will admin and will grant at least one Datamade admin owner access. You should have gotten an invite, Hannah.

**Comment by shrayshray** [comment]
@hancush can you confirm you got the invite to Metro’s new GitHub? We’re curious what the next steps for the migration are.

**Comment by hancush** [comment]
@shrayshray Yes, we did. We'll be off Friday through January 4, so we we will likely pick up this work in January.

**Comment by hancush** [comment]
HCG to check in on whether there's a better way to make a GH service account than a shared regular account, will send rec to Omar.

**Comment by hancush** [comment]
Looks like a shared account with readonly access is the way to go.
