### ISSUE TITLE
Store analytics remotely

### ISSUE THREAD

**Issue by antidipyramid** [Metro-Records/la-metro-councilmatic#814]
After creating a management command to generate tag analytics (#811), we should store the output to a remote location and/or email it to someone

**Comment by hancush** [comment]
Hey, @shrayshray! We're thinking through how these tag analytics reports should be delivered to you. I think I remember you saying Metro uses Dropbox – would it be convenient for us to post the reports to a shared Dropbox? Then, you all could manage access (and even your own email notifications) on your end, and have an archive of past reports handy. 

Let me know what you think!

**Comment by hancush** [comment]
Steps to upload a file to Google Drive:

- Create a service account following the instructions in the first section of this blog post: https://www.twilio.com/blog/2017/02/an-easy-way-to-read-and-write-to-a-google-spreadsheet-in-python.html
  - Be sure to follow the project / service account naming conventions outlined in https://github.com/datamade/how-to/issues/178#issue-815551873
- Create a reports folder in Google Drive and share it with DataMade, Shelly, Omar, [boardreport@metro.net](mailto:boardreport@metro.net), and your service account
- Encrypt and add your client secret to version control
- Use the Google API Python library to upload generated reports to your reports folder
  - Authentication example:
    - Part 1: https://github.com/security-force-monitor/sfm-cms/blob/bdf72bee05fb9842353a563e110d9fb70aa92afe/sfm_pc/management/commands/import_google_doc.py#L9
    - Part 2: https://github.com/security-force-monitor/sfm-cms/blob/bdf72bee05fb9842353a563e110d9fb70aa92afe/sfm_pc/management/commands/import_google_doc.py#L181-L181
    - Part 3: https://github.com/security-force-monitor/sfm-cms/blob/master/sfm_pc/management/commands/import_google_doc.py#L321-L324
   - Uploading will probably look something like this: https://developers.google.com/drive/api/v3/manage-uploads#python

**Comment by hancush** [comment]
@hancush to run May report and share access to Drive with Metro, then close.

**Comment by shrayshray** [comment]
@hancush there are many, MANY, copies of the monthly report .csv in the [Google Drive folder](https://drive.google.com/drive/folders/1iC4IhGGlzMNGKtAWWgi6HOSZ7QYoUEiR?usp=sharing) - is this expected? 
![image](https://user-images.githubusercontent.com/28063988/172256146-b1a1a221-02d6-4cd8-8010-bacfb4116fe8.png)

**Comment by hancush** [comment]
@shrayshray Hmm, we'll take a look.

**Comment by hancush** [comment]
It looks like this started behaving when I deployed the upgrade!
