### ISSUE TITLE
Board correspondence is missing from the board agendas site

### ISSUE THREAD

**Issue by hancush** [Metro-Records/la-metro-councilmatic#904]
Compare list of board correspondence items from Legistar to our search index. Do we have records that are not showing, or are we failing to scrape all records?

**Comment by hancush** [comment]
There are 79 reports of type board correspondence in Legistar, but we only have 25 in the database, and only 9 are showing up on the site.

So, I'll take a look at both the scraper and our LAMetroBill filter to see where they're getting lost.

**Comment by hancush** [comment]
The board correspondence lost in the scrape is not coming through because it does not have a title. @shrayshray @neilarellano @camachoo, is it possible to give titles to these reports? If not, we can programmatically generate them if you want to bring in all board correspondence and you expect it may not all have a title.

**Comment by hancush** [comment]
We'll add a reasonable default for board correspondence without a title, preferring the given title if one exists in Legistar. Double check to confirm bill will resolve to same entity if title changes.

**Comment by antidipyramid** [comment]
@hancush After pairing with @xmedr on this issue, we had two follow up questions:

1. Have all the problematic board correspondences been given names in Legistar?
2. Should we write a formal test for this new logic or just verify manually?

**Comment by hancush** [comment]
@antidipyramid They have not! Is there an existing test infrastructure? If so, writing a test would be great!

**Comment by antidipyramid** [comment]
@hancush Yes, here are metro tests in the scrapers repo (last updated 3 years ago 🙂) that we can add to. 

Thanks!

**Comment by hancush** [comment]
Naming convention: "Board Correspondence ${FILE ID}"

**Comment by hancush** [comment]
We now have 84 pieces of board correspondence indexed!
