### ISSUE TITLE
Migrate to ElasticSearch and Heroku

### ISSUE THREAD

**Issue by hancush** [Metro-Records/la-metro-councilmatic#911]

**Comment by hancush** [comment]
HCG to check whether all board reports are being indexed

**Comment by neilarellano** [comment]
Hi team! I wanted to check if the heroku staging site is supposed to be fully functional. Please advise.

**Comment by hancush** [comment]
@neilarellano So sorry for the delay! It does not look like the deployed search index contains all documents. I'll look into this in March.

**Comment by hancush** [comment]
Metro is going to monitor during agenda postings in September and will reach out to DataMade if they would like further guidance on testing.

**Comment by hancush** [comment]
@antidipyramid to draft list of next steps for cutover!!

**Comment by hancush** [comment]
We'll get everything locked and loaded for launch. Metro with coordinate DNS change with ITS for Dec. 1.

**Comment by neilarellano** [comment]
Hi @hancush! Do we have details on what we need to provide our ITS team for the cutover?

Also, we have a Measure M Independent Taxpayer Oversight Committee Meeting on December 6th. Maybe we can move the cutover for after that meeting.

@camachoo What do you think?

**Comment by hancush** [comment]
@antidipyramid Can you share documentation on managing custom domains on Heroku, please?

**Comment by antidipyramid** [comment]
@hancush Sure, I can link to it [here](https://devcenter.heroku.com/articles/custom-domains#configuring-dns-for-subdomains) and also send it over in an email.

**Comment by neilarellano** [comment]
Hi @antidipyramid ,

Are you able to send it over via email please? Please let us know exactly the DNS records we need to change and add for the migration so that we can forward it to our ITS team.

Thanks!

**Comment by antidipyramid** [comment]
A checklist to track progress during the transition:

- [x] Provision a Councilmatic production instance on Heroku
- [x] Provision a new production Dashboard instance on AWS
- [x] Bring the `heroku` branches of both the Councilmatic and Dashboard Github repos up to date
- [x] Find a suitable time and date (preferably on off-peak hours) to update the DNS (Dec. 6)
- [ ] Deploy production versions of the Councilmatic and Dashboard apps
- [ ] Update the app deployment pipelines from Github
- [ ] Create a full backup of the current servers and databases
- [ ] Update the DNS entry
- [ ] Bring old servers down (after trial period of one week)

**Comment by antidipyramid** [comment]
For everyone's reference, here are live links to the new instances:

- [staging dashboard](https://la-metro-dashboard-heroku.datamade.us)
- [production dashboard](https://la-metro-dashboard-heroku-prod.datamade.us)
- [staging councilmatic](https://la-metro-councilmatic-staging.herokuapp.com/)
- [production councilmatic](https://la-metro-councilmatic-prod-2377310f8771.herokuapp.com/)

@shrayshray @camachoo @neilarellano

**Comment by antidipyramid** [comment]
@hancush Looks like everything is in place for the Dec. 7 cutover. We've completed all of our pre-DNS update to-do's.

**Comment by antidipyramid** [comment]
Dec 8 update: Site is working as expected. After one week (Dec. 14), we'll bring the old servers down.

**Comment by antidipyramid** [comment]
Dec 15 update: old AWS servers have been stopped. The switch to Heroku is complete!
