### ISSUE TITLE
Live stream links are visible after meeting conclusion

### ISSUE THREAD

**Issue by hancush** [Metro-Records/la-metro-councilmatic#925]
Per @neilarellano:

---

We were having issues earlier today where the view stream links for both English and Spanish streams are still showing even after the meeting ended. This was a short meeting but the view stream links showed up for another 20 minutes or so. Are we able to check the logs for this one to check?

**Comment by hancush** [comment]
My response:

---

A couple of thoughts:

(1) Was the meeting removed from http://metro.granicus.com/running_events.php when it concluded?
(2) Did the meeting run for less than 20 minutes? If so, it would have continued to show with a generic broadcast link until 20 minutes past its start time. This is logic we put in place to account for late starts, but it needs updating if we expect meetings less than 20 minutes in length.

Let me know.

**Comment by hancush** [comment]
Per @camachoo, meetings under 20 minutes are "not a common occurrence, but it does happen."

We should update the `potentially_current` meetings to only show meetings that are not streaming past their start time if they have not yet been broadcast.

**Comment by xmedr** [comment]
@hancush I've got a proposal for this. I’m thinking the update that we make to [potentially_current_meetings](https://github.com/Metro-Records/la-metro-councilmatic/blob/master/lametro/models.py#L628) is something like:
```
statuses = ["cancelled", "passed"]

return cls.objects.filter(
            start_time__gte=six_hours_ago, start_time__lte=five_minutes_from_now
        ).exclude(status__in = statuses)
```
This way, if a meeting is not streaming past it's start time, but is labelled as "passed", it won't be shown. That would account for those short meetings. How does that sound?

**Comment by hancush** [comment]
@xmedr Interesting idea. How is event status set? Will it always be updated immediately after a meeting concludes?

**Comment by xmedr** [comment]
@hancush Ah, it looks like there's [lines in the events scraper](https://github.com/Metro-Records/scrapers-lametro/blob/92a440f274d65b881351bc8ebf5e5ce97575a40b/lametro/events.py#L218) that's setting that, so no I don't think it would be updated right after a meeting ends.
    
So based on "if they have not yet been broadcast", I've seen that the property [`has_passed`](https://github.com/Metro-Records/la-metro-councilmatic/blob/main/lametro/models.py#L791) checks for if the broadcast has been `observed`. And since I can't filter on a property, maybe something like:

```
return cls.objects.filter(
    start_time__gte=six_hours_ago, start_time__lte=five_minutes_from_now
  ).exclude(status="cancelled").exclude(broadcast__observed=True)
```

Though, I'm hesitant because I haven't found where `observed` is set to true. It could be the moment a meeting starts, right when it ends, or well after it ends (like the status). What do you think?

**Comment by hancush** [comment]
@xmedr `observed` [defaults to True](https://github.com/Metro-Records/la-metro-councilmatic/blob/5931c6debd49c8bd4c7286f20866f261c1520bc5/lametro/models.py#L880). There is a management command that [checks for a streaming meeting and creates a corresponding EventBroadcast object](https://github.com/Metro-Records/la-metro-councilmatic/blob/c913c404d3a0ae9542950c6ca978f1a550621c1c/lametro/management/commands/check_current_meeting.py), which is [run every 10 minutes](https://github.com/Metro-Records/la-metro-dashboard/blob/main/dags/check_meeting_broadcast.py) by the dashboard. So, meetings that start streaming should have a corresponding broadcast where observed is true 10 minutes or less after the stream begins.

Given all that, I think your proposal makes sense! (BTW, you can combine the exclude calls into one exclude with multiple kwargs.)
