### ISSUE TITLE
Repeating Fiscal Year Ranges

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#950]
Greetings Datamade Team!

We noticed an issue within the Board Report search function where filtering by fiscal year displays repeating fiscal year ranges.
![image](https://user-images.githubusercontent.com/110051034/223581625-528cb0f9-03bc-44c0-be36-8b11b7fd2011.png)

**Comment by xmedr** [comment]
Hey @neilarellano!

As an update, @hancush and I paired on this and found that the production SES instance is giving us some errors, which may be part of the issue here. She's going to do some more digging on this and see what comes up.

**Comment by hancush** [comment]
Done and deployed!
