### ISSUE TITLE
PDF Viewer Display Error

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#952]
Greetings Datamade Team!

We are getting this error for the PDF viewer. It seems like the items are displaying correctly on the right side, but the PDF viewer is giving us this error.

![image](https://user-images.githubusercontent.com/110051034/224463864-062d7ca6-5319-4cbe-a165-a084e09b7d5a.png)

**Comment by hancush** [comment]
This had to do with the file name including a smart quote, which could not properly be returned as a header. I updated our file server to escape non-Unicode characters and the agenda is now being displayed properly. See https://boardagendas.metro.net/event/independent-citizens-advisory-and-oversight-f860c853dfc8/
