### ISSUE TITLE
New Member Headshot and Bio Disappeared

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#957]
We recently had changes in Committee members and it seems like Katy’s headshot and bio disappeared after we made these changes in Legistar. Please see below:
 
 
![image](https://user-images.githubusercontent.com/110051034/229583945-b5d47fa0-67cd-4314-a6f3-dd073aa197f9.png)

Are we able to investigate on why this happened?
As for now, I will go ahead and re-add their headshot/bio to resolve the issue.

**Comment by neilarellano** [comment]
Hi Team,

I re-added the bio and headshot earlier today. I just checked again right now and it seems like the headshot and bio are gone again. Please investigate.

Thank you!

**Comment by hancush** [comment]
@xmedr It looks like storing the bio and headshot on the base opencivicdata model causes them to be erased when that base model changes, e.g., memberships are changed. Looks like [there's a headshot field on the Person model from django-councilmatic](https://github.com/datamade/django-councilmatic/blob/bbc8e5d912f3ae2ff9ee9f742c96b5974104d28a/councilmatic_core/models.py#L63), but we'll need to add a biography field, as well. Can you submit a django-councilmatic PR with that change?

**Comment by hancush** [comment]
@neilarellano Fix is in. I've added her headshot back, but can't find the bio text. Want to update it?

**Comment by hancush** [comment]
Absolutely. Thanks, @neilarellano!

**Comment by neilarellano** [comment]
I can confirm that the bio and headshot stays after making changes to committee members! Thanks!
