### ISSUE TITLE
On 7/1/23, remove FY23 calendar

### ISSUE THREAD

**Issue by shrayshray** [Metro-Records/la-metro-councilmatic#966]
On 7/1/23 (or Monday 7/3/23) remove the FY23 calendar linked next to "Upcoming Meetings" and "Recent Meetings".
![image](https://user-images.githubusercontent.com/28063988/235739340-cee68b64-4d3b-4c8f-b2ab-338a3da47944.png)

**Comment by hancush** [comment]
@shrayshray Is it ok if we remove this, this Friday, 6/30, since the first is a Saturday?

**Comment by shrayshray** [comment]
@hancush yes, removing on Friday is fine. Thank you!

**Comment by hancush** [comment]
Done and deployed.
