### ISSUE TITLE
Search for Project results in error after clicking "tag search"

### ISSUE THREAD

**Issue by camachoo** [Metro-Records/la-metro-councilmatic#972]
Type "project" in the search bar on the home page.
Click enter.
Click "Tag Search"
![image](https://github.com/Metro-Records/la-metro-dashboard/assets/28767738/eae49161-41e2-43a2-b9ef-e0d82c1ec626)

**Comment by hancush** [comment]
I think this term is associated with so many board reports that it's breaking Solr. Not sure how to fix, but can look into it.

**Comment by shrayshray** [comment]
I noticed the top tagging terms are all experiencing the same issue. See attached for report on top tagging terms (thanks to the reports Datamade is generating for us!). It does seem like an issue to have this occurring for the most popular terms. There is work to be done on our side to evaluate whether these terms are over-tagging, and on the Datamade side to see if this level of tagging can be accommodated. Even if over-tagging is occuring now, it's possible we'll have this amount of instances in the future.
[report-2023-05-08-board-report-tag-analytics.pdf](https://github.com/Metro-Records/la-metro-councilmatic/files/11503147/report-2023-05-08-board-report-tag-analytics.pdf)

**Comment by hancush** [comment]
@antidipyramid is going to run the full scrape and index all board reports on the Heroku instance, then check to see whether the switch to Elasticsearch resolves this problem.

Let us know what you find out!

**Comment by antidipyramid** [comment]
@hancush I'm getting this error after a full scrape:

<img width="621" alt="Screen Shot 2023-09-06 at 2 30 53 PM" src="https://github.com/Metro-Records/la-metro-councilmatic/assets/36973363/10bcd70b-b38a-4f00-956c-024f04f916ef">

Do we just have to increase storage on the AWS server?

**Comment by hancush** [comment]
Try `sudo docker system prune` first, then run `df -ah` to see how much space you have left.

**Comment by antidipyramid** [comment]
@hancush After `docker system prune`:

<img width="591" alt="Screen Shot 2023-09-08 at 9 38 47 AM" src="https://github.com/Metro-Records/la-metro-councilmatic/assets/36973363/e4fafbd2-2539-49a9-8d09-7f541631edc9">
<img width="472" alt="Screen Shot 2023-09-08 at 9 39 34 AM" src="https://github.com/Metro-Records/la-metro-councilmatic/assets/36973363/f629a077-d8fa-4e91-845f-79382d9628a6">

Currently the instance has 20GB of storage. Our current staging instance also has 20GB but prod has 50GB. 

Should we up the storage?

**Comment by antidipyramid** [comment]
@hancush Upped the storage on the EC2 instance. The full scrape now completes successfully.

After a tag search for `Project`, we get this error:

<img width="1426" alt="Screen Shot 2023-09-11 at 8 55 37 AM" src="https://github.com/Metro-Records/la-metro-councilmatic/assets/36973363/457d6677-26dd-44da-b605-a8a16a7e946f">

Seems like we're not forming these search queries correctly. Or they're at least extremely inefficient.

**Comment by hancush** [comment]
@antidipyramid This method constructs and runs those queries: https://github.com/Metro-Records/la-metro-councilmatic/blob/70b6e171b9b0033511b55c43ddd8f87a417a8179/lametro/forms.py#L63

There's definitely a better way to do this. Are you able to try some different approaches this week?
