### ISSUE TITLE
Missing "Download All Attachments" Button on Reports

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#981]
Hi Datamade Team,

We just noticed that the button to "Download All Attachments" in the page for reports disappeared. Please see below:
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/51941e9b-a6f9-42c6-b104-87cfb4662b89)

Are we able to bring this button back? Thank you!

**Comment by shrayshray** [comment]
To clarify, the button is "Download Board Report and Attachments". @hancush Could Datamade please prioritize investigating this?

**Comment by hancush** [comment]
@shrayshray Yes, I'll have a look today.

**Comment by hancush** [comment]
Hi, @shrayshray – I've made a tweak to the upgraded dashboard API, which I believe has resolved this. Can you confirm?

**Comment by shrayshray** [comment]
@hancush it's back up and working as expected now, thank you!
