### ISSUE TITLE
Using Google Translate impacts access to navigation

### ISSUE THREAD

**Issue by shrayshray** [Metro-Records/la-metro-councilmatic#991]
I noticed today that when using the Google Translate tool embedded on the site, the tool covers up the top navigation. Can you look into what can be adjusted to ensure navigation options are still visible for people translating the site?
![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/28063988/99f63be5-7c26-4129-a134-a77988826f7b)

**Comment by hancush** [comment]
Done and deployed.
