### ISSUE TITLE
Committee Member Duplicates

### ISSUE THREAD

**Issue by neilarellano** [Metro-Records/la-metro-councilmatic#995]
Hi Team!

We changed a member's name within Legistar from "Gloria Roberts (Interim)" to "Gloria Roberts". The site now reflects both names for all the Committees. Are we able to remove the entry for "Gloria Roberts (Interim)"?

![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/1caf56c3-fe44-470c-89da-cda29397e5b7)

![image](https://github.com/Metro-Records/la-metro-councilmatic/assets/110051034/93ea207b-6c9a-4bc5-9cf1-99870c3b9eeb)

Thank you!

**Comment by neilarellano** [comment]
@hancush are we able to look into this one please?

**Comment by hancush** [comment]
@antidipyramid Hm, I would have expected the old version to be removed by the `pupa clean` command. Can you look into this next week?

**Comment by antidipyramid** [comment]
Will do @hancush

**Comment by hancush** [comment]
I manually removed this membership while we finish up changes in https://github.com/opencivicdata/pupa/pull/350
